<?php
    date_default_timezone_set("Europe/Paris");
    define("JOURS",[
        "lundi",
        "mardi",
        "mercredi",
        "jeudi",
        "vendredi",
        "samedi",
        "dimanche"
    ]);

    define("CREANEAUX",[
        [
            [8,12],
            [14,19]
        ],
        [
            [8,12],
            [14,19]
        ],
        [
            [8,12],
            [14,19]
        ],
        [
        [8,12],
            [14,19]
        ],
        [
            [8,12],
            [14,19]
        ],
        [
            [],
            []
        ],
        [
            [],
            []
        ]
    ]);